BEGIN TRANSACTION;
CREATE TABLE `codelist` (
	`category`	TEXT NOT NULL,
	`code`	INTEGER NOT NULL,
	`region1`	TEXT NOT NULL,
	`region2`	TEXT NOT NULL,
	`branch`	TEXT NOT NULL,
	`area`	TEXT NOT NULL,
	`color`	TEXT NOT NULL,
	PRIMARY KEY(code)
);
INSERT INTO `codelist` VALUES('D',201,'서울권','강남','서강남','논현동,신사동,압구정동','ff8c8c');
INSERT INTO `codelist` VALUES('A',202,'서울권','강동','서강동','성내동,암사동,천호동','ff8c8c');
INSERT INTO `codelist` VALUES('A',203,'서울권','강서','북강서','가양동,개화동,등촌동,마곡동,방화동,염창동','ff8c8c');
INSERT INTO `codelist` VALUES('A',204,'서울권','금천','금천','금천구','ff8c8c');
INSERT INTO `codelist` VALUES('A',205,'서울권','구로','동구로','가리봉동,구로동,신도림동','ff8c8c');
INSERT INTO `codelist` VALUES('G',206,'서울권','은평','은평','은평구','ff8c8c');
INSERT INTO `codelist` VALUES('B',207,'서울권','노원','북노원','상계동,중계동','ff8c8c');
INSERT INTO `codelist` VALUES('B',208,'서울권','도봉','도봉','도봉구','ff8c8c');
INSERT INTO `codelist` VALUES('D',209,'서울권','서초','동서초','내곡동,서초동,신원동,양재동,염곡동,우면동,원지동','ff8c8c');
INSERT INTO `codelist` VALUES('G',210,'서울권','서대구','서대구','서대문구','ff8c8c');
INSERT INTO `codelist` VALUES('A',211,'서울권','송파','북송파','방이동,삼전동,석촌동,송파동,신천동,오륜동,잠실동,풍락동','ff8c8c');
INSERT INTO `codelist` VALUES('G',212,'서울권','용산','동용산','갈월동,남영동,동자동,용산동,이촌동,이태원동,한강로,후암동','ff8c8c');
INSERT INTO `codelist` VALUES('A',213,'서울권','영등포','동영등포','당산동,도림동,대림동,문래동,신길동','ff8c8c');
INSERT INTO `codelist` VALUES('G',214,'서울권','종로','종로','종로구','ff8c8c');
INSERT INTO `codelist` VALUES('G',215,'서울권','중구','남중구','동중구(G228)제외 전지역 *을지로1~4가,동국대,충정로1가 50~80','ff8c8c');
INSERT INTO `codelist` VALUES('A',216,'서울권','동작','동작','동작구','ff8c8c');
INSERT INTO `codelist` VALUES('B',217,'서울권','광진','광진','광진구','ff8c8c');
INSERT INTO `codelist` VALUES('A',218,'서울권','양천','동양천','목동,신월2,4,6동 *목동아파트1~7단지까지 목동임','ff8c8c');
INSERT INTO `codelist` VALUES('G',219,'서울권','강북','강북','강북구','ff8c8c');
INSERT INTO `codelist` VALUES('A',220,'서울권','관악','북관악','구 신림동,난곡동,난향동,대학동,미성동,삼성동,서림동,서원동,신림동,신사동,신원동,조원동','ff8c8c');
INSERT INTO `codelist` VALUES('B',221,'서울권','동대문','동대문','동대문구','ff8c8c');
INSERT INTO `codelist` VALUES('G',222,'서울권','마포','서마포','동교동,망원동,상암동,서교동,성산동,연남동,중동,합정동','ff8c8c');
INSERT INTO `codelist` VALUES('B',223,'서울권','중랑','중랑','중랑구','ff8c8c');
INSERT INTO `codelist` VALUES('B',224,'서울권','성북','성북','성북구','ff8c8c');
INSERT INTO `codelist` VALUES('G',225,'서울권','성동','성동','성동구','ff8c8c');
INSERT INTO `codelist` VALUES('D',226,'서울권','강남','동강남','대치동,삼성동,역삼동,청담동','ff8c8c');
INSERT INTO `codelist` VALUES('G',227,'서울권','용산','서용산','도원동,동빙고동,문배동,보광동,산천동,서개동,서빙고동,신계동,신창동,용문동,원효로,주성동,청암동,청파동,한남동,효창동','ff8c8c');
INSERT INTO `codelist` VALUES('G',228,'서울권','중구','동중구','광이동,무학동,묵정동,신당동,쌍림동,장충동,황학동,흥인동,다산동,약수동,청구동,동화동,주교동,오장동,방산동,을지로5~7가','ff8c8c');
INSERT INTO `codelist` VALUES('D',229,'서울권','서초','남서초','반포동,방배동,잠원동','ff8c8c');
INSERT INTO `codelist` VALUES('A',230,'서울권','영등포','서영등포','양평동,양화동,여의도동,영등포동,영등포본동','ff8c8c');
INSERT INTO `codelist` VALUES('A',231,'서울권','송파','남송파','가락동,거여동,마천동,문정동,오금동,장지동','ff8c8c');
INSERT INTO `codelist` VALUES('G',232,'서울권','마포','동마포','공덕동,구수동,노고산동,당인동,도화동,대흥동,마포동,상수동,신공덕동,신수동,신정동,아현동,염리동,용강동,창전동,토정동,하중동,현석동','ff8c8c');
INSERT INTO `codelist` VALUES('A',233,'서울권','강서','남강서','공항동,과해동,내발산동,우장산동,오곡동,오쇠동,외발산동,화곡동','ff8c8c');
INSERT INTO `codelist` VALUES('B',234,'서울권','노원','남노원','공릉동,월계동,하계동','ff8c8c');
INSERT INTO `codelist` VALUES('A',235,'서울권','구로','서구로','궁동,고척동,개봉동,오류동,온수동,천왕동,항동','ff8c8c');
INSERT INTO `codelist` VALUES('A',236,'서울권','관악','남관악','구봉천동,낙성대동,남현동,보라매동,성현동,은천동,인헌동,중앙동,청림동,청룡동,행운동 *서울대학교','ff8c8c');
INSERT INTO `codelist` VALUES('A',237,'서울권','강동','동강동','강일동,고덕동,길동,둔촌동,명일동,상일동','ff8c8c');
INSERT INTO `codelist` VALUES('A',238,'서울권','양천','서양천','신월1,3,5,7동,신정동 * 목동8~14단지까지 신정동임','ff8c8c');
INSERT INTO `codelist` VALUES('D',241,'서울권','강남','남강남','개포동,도곡동,수서동,세곡동,율현동,일원동,자곡동,포이동','ff8c8c');
INSERT INTO `codelist` VALUES('E',301,'경기권','일산','서일산','일산서구,일산동 산들마을 3,5,6단지','fff557');
INSERT INTO `codelist` VALUES('B',302,'경기권','이천','이천','여주시,이천시,장호원읍','fff557');
INSERT INTO `codelist` VALUES('E',303,'경기권','부천','서부천','원미구(상동,중동)','fff557');
INSERT INTO `codelist` VALUES('B',304,'경기권','성남','성남중원','중원구','fff557');
INSERT INTO `codelist` VALUES('B',305,'경기권','수원','동수원','영통구','fff557');
INSERT INTO `codelist` VALUES('A',306,'경기권','안산','서안산','단원구','fff557');
INSERT INTO `codelist` VALUES('B',307,'경기권','안양','동안양','동안구(관양동,귀인동,부림동,평안동,평촌동)','fff557');
INSERT INTO `codelist` VALUES('D',308,'경기권','의정부','의정부','의정부시','fff557');
INSERT INTO `codelist` VALUES('E',309,'경기권','파주','교하','교하동,다율동,연다산동,동패동,야당동,문발동,산남동,오도동,신촌동,송촌동,목동동,와동동,당하동,상지석동,하지석동,서패동,조리읍,운정동','fff557');
INSERT INTO `codelist` VALUES('A',310,'경기권','평택','평택','평택시','fff557');
INSERT INTO `codelist` VALUES('E',311,'경기권','파주','파주','탄현면,금촌동,아동동,야동동,문산읍,금능동,검산동,맥금동,월롱면,법원읍,파주읍,광탄면,적성면,파평면,군내면,장단면,진동면,진서면','fff557');
INSERT INTO `codelist` VALUES('D',312,'경기권','하남','하남','하남시','fff557');
INSERT INTO `codelist` VALUES('D',313,'경기권','구리','구리','구리시','fff557');
INSERT INTO `codelist` VALUES('E',314,'경기권','김포','김포','김포시','fff557');
INSERT INTO `codelist` VALUES('D',315,'경기권','포천','포천','포천시','fff557');
INSERT INTO `codelist` VALUES('A',316,'경기권','광명','광명','광명시','fff557');
INSERT INTO `codelist` VALUES('B',317,'경기권','군포','군포','군포시','fff557');
INSERT INTO `codelist` VALUES('D',318,'경기권','양주','양주','양주시','fff557');
INSERT INTO `codelist` VALUES('E',319,'경기권','인천','남인천','남동구(고잔동,남촌동,논현동,도림동,만수동,서창동,수산동,운연동,장수동)','fff557');
INSERT INTO `codelist` VALUES('E',320,'경기권','인천','계양','계양구','fff557');
INSERT INTO `codelist` VALUES('B',321,'경기권','용인','처인','처인구','fff557');
INSERT INTO `codelist` VALUES('A',322,'경기권','화성','북화성','기배동,기산동,기안동,남양동,마도면,매송면,무송동,문호동,반월동,반정동,배양동,병점동,봉담읍,북양동,비봉면,서산면,송림동,송산동,송산면,수화동,시동,신남동,신외동,안녕동,안석동,온석동,원천동,장덕동,장전동,진안동,활초동,화산동,황계동,화성시 반월동 삼성전자 화성사업소 H1','fff557');
INSERT INTO `codelist` VALUES('E',323,'경기권','일산','덕양','덕양구','fff557');
INSERT INTO `codelist` VALUES('E',324,'경기권','인천','인천남구','남구','fff557');
INSERT INTO `codelist` VALUES('E',325,'경기권','인천','인천서구','서구','fff557');
INSERT INTO `codelist` VALUES('A',326,'경기권','시흥','남시흥','거모동,군자동,월곶동,정왕동,죽율동,안산시(대부남동,대부동동,대부북동,선감동)','fff557');
INSERT INTO `codelist` VALUES('A',327,'경기권','안성','안성','안성시','fff557');
INSERT INTO `codelist` VALUES('B',328,'경기권','양평','양평','양평군,여주시(금사면,산북면)','fff557');
INSERT INTO `codelist` VALUES('B',329,'경기권','오산동탄','오산동탄','오산시,화성시(능동,동탄동,동탄면,반송동,석우동,화성시 석우동 삼성전자 화성사업소 H2,H3)','fff557');
INSERT INTO `codelist` VALUES('E',330,'경기권','부천','남부천','소사구,오정구','fff557');
INSERT INTO `codelist` VALUES('E',331,'경기권','일산','동일산','일산동구,중산동 산들마을 1,2단지','fff557');
INSERT INTO `codelist` VALUES('A',332,'경기권','안산','동안산','상록구','fff557');
INSERT INTO `codelist` VALUES('D',333,'경기권','남양주','서남양주','수동면,오남읍,진건읍,진접읍,퇴계원면,화도읍','fff557');
INSERT INTO `codelist` VALUES('B',334,'경기권','성남','동분당','분당동,서현동,수내동,야탑동,율동,이매동','fff557');
INSERT INTO `codelist` VALUES('B',335,'경기권','수원','서수원','권선구','fff557');
INSERT INTO `codelist` VALUES('B',336,'경기권','용인','수지','수지구(고기동,동천동,상현동,성복동,신봉동,죽전동,풍덕천동) *기흥구 보정동 롯데마트 수지점,진산마을 삼성래미안5,6,7차','fff557');
INSERT INTO `codelist` VALUES('B',337,'경기권','안양','서안양','만안구','fff557');
INSERT INTO `codelist` VALUES('D',338,'경기권','동두천','동두천','동두천시,연천구','fff557');
INSERT INTO `codelist` VALUES('E',340,'경기권','인천','부평','부평구','fff557');
INSERT INTO `codelist` VALUES('B',341,'경기권','용인','기흥','기흥구','fff557');
INSERT INTO `codelist` VALUES('B',342,'경기권','경기광주','경기광주','경기광주시','fff557');
INSERT INTO `codelist` VALUES('A',343,'경기권','의왕과천','의왕과천','의왕시,과천시','fff557');
INSERT INTO `codelist` VALUES('E',344,'경기권','인천','인천연수구','연수구','fff557');
INSERT INTO `codelist` VALUES('E',345,'경기권','인천','인천중구','동구,중구,옹진군','fff557');
INSERT INTO `codelist` VALUES('A',346,'경기권','시흥','북시흥','계수동,과림동,광석동,금이동,논곡동,능곡동,도창동,대야동,목감동,무지내동,물왕동,미산동,매화동,방산동,신현동,신천동,안현동,은행동,장곡동,장현동,조남동,포동,하상동,화정동,하중동','fff557');
INSERT INTO `codelist` VALUES('B',347,'경기권','안양','북안양','동안구(달안동,범계동,부흥동,비산동,신촌동,호계동,갈산동)','fff557');
INSERT INTO `codelist` VALUES('E',348,'경기권','인천','강화','강화군','fff557');
INSERT INTO `codelist` VALUES('W',349,'경기권','가평','가평','가평군','fff557');
INSERT INTO `codelist` VALUES('A',350,'경기권','화성','남화성','양감면,우정읍,장안면,정남면,팔탄면,향남읍','fff557');
INSERT INTO `codelist` VALUES('E',351,'경기권','부천','동부천','원미구(심곡1~3동,소사동,역곡1~2동,도당동,약대동,원미동,춘의동)','fff557');
INSERT INTO `codelist` VALUES('B',352,'경기권','성남','성남수정','수정구','fff557');
INSERT INTO `codelist` VALUES('D',353,'경기권','남양주','동남양주','가운동,금곡동,도농동,별내동,별내읍,삼패동,수석동,이패동,일패동,양정동,와부읍,조안면,지금동,편내동,호평동','fff557');
INSERT INTO `codelist` VALUES('B',354,'경기권','성남','서분당','구미동,궁내동,금곡동,동원동,대장동,백현동,삼평동,석운동,운중동,정자동,판교동,하산운동','fff557');
INSERT INTO `codelist` VALUES('B',355,'경기권','수원','남수원','팔달구','fff557');
INSERT INTO `codelist` VALUES('B',356,'경기권','수원','북수원','장안구','fff557');
INSERT INTO `codelist` VALUES('E',357,'경기권','인천','인천중앙','남동구(간석동,구월동)','fff557');
INSERT INTO `codelist` VALUES('M',401,'충청권','대전','서대전','서구','8ae249');
INSERT INTO `codelist` VALUES('M',402,'충청권','서산','서산','서산시','8ae249');
INSERT INTO `codelist` VALUES('M',403,'충청권','천안','동천안','동남구(구룡동,구성동,광덕면,다가동,동면,목천읍,문화동,대흥동,병천면,봉명동,북면,사직동,삼룡동,성남면,성황동,수신면,신방동,신부동,안서동,영성동,오룡동,용곡동,유량동,와촌동,원성동,청당동,청수동,풍세면),서북구 와촌동','8ae249');
INSERT INTO `codelist` VALUES('M',404,'충청권','청주','서청주','흥덕구,서원구','8ae249');
INSERT INTO `codelist` VALUES('M',405,'충청권','충주','충주','충주시','8ae249');
INSERT INTO `codelist` VALUES('M',406,'충청권','보령','보령','보령시','8ae249');
INSERT INTO `codelist` VALUES('M',407,'충청권','금산','금산','금산군','8ae249');
INSERT INTO `codelist` VALUES('M',408,'충청권','논산','논산','논산시,계룡시','8ae249');
INSERT INTO `codelist` VALUES('M',409,'충청권','예산','예산','예산군','8ae249');
INSERT INTO `codelist` VALUES('M',410,'충청권','홍성','홍성','홍성군','8ae249');
INSERT INTO `codelist` VALUES('M',411,'충청권','대전','동대전','대덕구','8ae249');
INSERT INTO `codelist` VALUES('M',412,'충청권','당진','당진','당진군','8ae249');
INSERT INTO `codelist` VALUES('M',413,'충청권','아산','아산','아산시','8ae249');
INSERT INTO `codelist` VALUES('M',414,'충청권','공주','공주','공주시,세종시 장군면','8ae249');
INSERT INTO `codelist` VALUES('M',415,'충청권','청원','청원','청주시 상당구(낭성면,미원면,가덕면,남일면,문의면),청주시 서원구(남이면,현도면),청주시 흥덕구(오송읍,강내면,옥산면),청주시 청원구(내수읍,오창읍,북이면),증평군','8ae249');
INSERT INTO `codelist` VALUES('M',416,'충청권','음성','음성','음성군','8ae249');
INSERT INTO `codelist` VALUES('M',417,'충청권','영동','영동','영동군','8ae249');
INSERT INTO `codelist` VALUES('M',418,'충청권','청주','동청주','상당구,청원구','8ae249');
INSERT INTO `codelist` VALUES('M',419,'충청권','세종','세종','세종시','8ae249');
INSERT INTO `codelist` VALUES('M',420,'충청권','청양','청양','청양군','8ae249');
INSERT INTO `codelist` VALUES('M',421,'충청권','천안','서천안','서북구(두정동,부대동,불당동,백성동,성거읍,성성동,성정동,성환읍,신당동,쌍용동,업성동,입장면,직산읍,차암동)','8ae249');
INSERT INTO `codelist` VALUES('M',422,'충청권','태안','태안','태안군','8ae249');
INSERT INTO `codelist` VALUES('M',423,'충청권','부여','부여','부여군','8ae249');
INSERT INTO `codelist` VALUES('M',424,'충청권','대전','북대전','유성구','8ae249');
INSERT INTO `codelist` VALUES('M',425,'충청권','대전','남대전','동구,중구','8ae249');
INSERT INTO `codelist` VALUES('M',426,'충청권','서천','서천','서천구','8ae249');
INSERT INTO `codelist` VALUES('L',427,'충청권','제천','제천','제천시','8ae249');
INSERT INTO `codelist` VALUES('M',428,'충청권','진천','진천','진천군','8ae249');
INSERT INTO `codelist` VALUES('M',429,'충청권','보은','보은','보은군','8ae249');
INSERT INTO `codelist` VALUES('M',430,'충청권','괴산','괴산','괴산군','8ae249');
INSERT INTO `codelist` VALUES('M',431,'충청권','옥천','옥천','옥천군','8ae249');
INSERT INTO `codelist` VALUES('L',432,'충청권','단양','단양','단양군','8ae249');
INSERT INTO `codelist` VALUES('M',501,'경상권','거창','거창','거창군,함양군','49bce2');
INSERT INTO `codelist` VALUES('T',502,'경상권','경주','경주','경주시','49bce2');
INSERT INTO `codelist` VALUES('T',503,'경상권','김해','김해','김해시','49bce2');
INSERT INTO `codelist` VALUES('M',504,'경상권','구미','구미','구미시,군위군','49bce2');
INSERT INTO `codelist` VALUES('R',505,'경상권','대구','서대구','남구,서구,중구','49bce2');
INSERT INTO `codelist` VALUES('R',506,'경상권','창원','창원의창','의창구','49bce2');
INSERT INTO `codelist` VALUES('T',507,'경상권','경산','경산','경산시,청도군','49bce2');
INSERT INTO `codelist` VALUES('T',508,'경상권','안동','안동','안동시,영양군,청송군','49bce2');
INSERT INTO `codelist` VALUES('T',509,'경상권','사천','사천','사천시','49bce2');
INSERT INTO `codelist` VALUES('T',510,'경상권','진주','진주','진주시','49bce2');
INSERT INTO `codelist` VALUES('T',511,'경상권','통영','통영','통영시,경남 고성군','49bce2');
INSERT INTO `codelist` VALUES('R',512,'경상권','포항','북포항','북구,울릉군','49bce2');
INSERT INTO `codelist` VALUES('M',513,'경상권','상주','상주','상주시','49bce2');
INSERT INTO `codelist` VALUES('M',514,'경상권','영주','영주','영주시,봉화군','49bce2');
INSERT INTO `codelist` VALUES('T',515,'경상권','밀양','밀양','밀양시','49bce2');
INSERT INTO `codelist` VALUES('T',516,'경상권','하동','하동','하동군','49bce2');
INSERT INTO `codelist` VALUES('M',517,'경상권','김천','김천','김천시','49bce2');
INSERT INTO `codelist` VALUES('T',518,'경상권','양산','양산','양산시','49bce2');
INSERT INTO `codelist` VALUES('R',519,'경상권','영덕','영덕','영덕군','49bce2');
INSERT INTO `codelist` VALUES('K',520,'경상권','부산','부산북구','북구','49bce2');
INSERT INTO `codelist` VALUES('K',521,'경상권','부산','동래','동래구,연제구','49bce2');
INSERT INTO `codelist` VALUES('K',522,'경상권','부산','해운대','해운대구','49bce2');
INSERT INTO `codelist` VALUES('K',523,'경상권','부산','진구','부산진구','49bce2');
INSERT INTO `codelist` VALUES('K',524,'경상권','부산','중부산','동구,중구','49bce2');
INSERT INTO `codelist` VALUES('K',525,'경상권','부산','사하','사하구,서구','49bce2');
INSERT INTO `codelist` VALUES('K',526,'경상권','부산','사상','사상구','49bce2');
INSERT INTO `codelist` VALUES('R',527,'경상권','울산','남울산','남구','49bce2');
INSERT INTO `codelist` VALUES('T',528,'경상권','울산','동울산','동구','49bce2');
INSERT INTO `codelist` VALUES('T',529,'경상권','울산','울주','울주군','49bce2');
INSERT INTO `codelist` VALUES('R',530,'경상권','대구','동대구','동구','49bce2');
INSERT INTO `codelist` VALUES('T',531,'경상권','창원','마산','마산합포구,마산회원구','49bce2');
INSERT INTO `codelist` VALUES('T',532,'경상권','남해','남해','남해군','49bce2');
INSERT INTO `codelist` VALUES('T',533,'경상권','영천','영천','영천시','49bce2');
INSERT INTO `codelist` VALUES('T',534,'경상권','울진','울진','울진군','49bce2');
INSERT INTO `codelist` VALUES('T',535,'경상권','부산','금정','금정구,기장군','49bce2');
INSERT INTO `codelist` VALUES('T',536,'경상권','창원','진해','진해구','49bce2');
INSERT INTO `codelist` VALUES('K',537,'경상권','부산','남부산','남구,수영구','49bce2');
INSERT INTO `codelist` VALUES('T',538,'경상권','거제','거제','거제시,통영시 용남면(수도,어의리(어의도))','49bce2');
INSERT INTO `codelist` VALUES('M',539,'경상권','성주칠곡','성주칠곡','칠곡군,성주군','49bce2');
INSERT INTO `codelist` VALUES('T',540,'경상권','창녕','창녕','창녕군','49bce2');
INSERT INTO `codelist` VALUES('T',541,'경상권','합천','합천','합천군','49bce2');
INSERT INTO `codelist` VALUES('T',542,'경상권','의성','의성','의성군','49bce2');
INSERT INTO `codelist` VALUES('M',543,'경상권','문경','문경','문경시','49bce2');
INSERT INTO `codelist` VALUES('M',544,'경상권','예천','예천','예천군','49bce2');
INSERT INTO `codelist` VALUES('R',545,'경상권','대구','남대구','고령군,달서구,달성군','49bce2');
INSERT INTO `codelist` VALUES('T',546,'경상권','울산','북울산','북구','49bce2');
INSERT INTO `codelist` VALUES('K',547,'경상권','부산','부산강서','강서구','49bce2');
INSERT INTO `codelist` VALUES('K',548,'경상권','부산','영도','영도구','49bce2');
INSERT INTO `codelist` VALUES('T',549,'경상권','함안의령','함안의령','함안군,의령군','49bce2');
INSERT INTO `codelist` VALUES('R',550,'경상권','대구','대구수성','수성구,달성군 가창면','49bce2');
INSERT INTO `codelist` VALUES('R',552,'경상권','포항','남포항','남구','49bce2');
INSERT INTO `codelist` VALUES('T',554,'경상권','산청','산청','산청군','49bce2');
INSERT INTO `codelist` VALUES('R',556,'경상권','창원','창원성산','성산구','49bce2');
INSERT INTO `codelist` VALUES('T',558,'경상권','울산','중울산','중구','49bce2');
INSERT INTO `codelist` VALUES('R',560,'경상권','대구','북대구','북구,칠곡군 동명면','49bce2');
INSERT INTO `codelist` VALUES('J',601,'전라권','광주','남광주','남구,동구','e080f5');
INSERT INTO `codelist` VALUES('J',602,'전라권','남원','남원','남원시','e080f5');
INSERT INTO `codelist` VALUES('J',603,'전라권','목포','목포','목포시','e080f5');
INSERT INTO `codelist` VALUES('J',604,'전라권','순천','순천','순천시','e080f5');
INSERT INTO `codelist` VALUES('J',605,'전라권','여수','여수','여수시','e080f5');
INSERT INTO `codelist` VALUES('M',606,'전라권','익산','익산','익산시','e080f5');
INSERT INTO `codelist` VALUES('M',607,'전라권','전주','남전주','완산구,완주군','e080f5');
INSERT INTO `codelist` VALUES('J',608,'전라권','해남','해남','해남군','e080f5');
INSERT INTO `codelist` VALUES('J',609,'전라권','고흥','고흥','고흥군','e080f5');
INSERT INTO `codelist` VALUES('M',610,'전라권','정읍','정읍','정읍시,순창군(복흥면,쌍치면)','e080f5');
INSERT INTO `codelist` VALUES('M',611,'전라권','군산','군산','순산시','e080f5');
INSERT INTO `codelist` VALUES('J',612,'전라권','구례','구례','구례군,곡성군','e080f5');
INSERT INTO `codelist` VALUES('J',613,'전라권','나주','나주','나주시','e080f5');
INSERT INTO `codelist` VALUES('J',614,'전라권','광양','광양','광양시','e080f5');
INSERT INTO `codelist` VALUES('J',615,'전라권','담양','담양','담양군,장성군','e080f5');
INSERT INTO `codelist` VALUES('J',616,'전라권','강진','강진','강진군,완도군 고금면,생일면,약산면,완도군 금일읍','e080f5');
INSERT INTO `codelist` VALUES('M',617,'전라권','무주','무주','무주군','e080f5');
INSERT INTO `codelist` VALUES('M',618,'전라권','김제','김제','김제시','e080f5');
INSERT INTO `codelist` VALUES('J',619,'전라권','보성','보성','보성군','e080f5');
INSERT INTO `codelist` VALUES('J',620,'전라권','영광','영광','영광군','e080f5');
INSERT INTO `codelist` VALUES('J',621,'전라권','광주','북광주','북구','e080f5');
INSERT INTO `codelist` VALUES('J',622,'전라권','임실','임실','임실군','e080f5');
INSERT INTO `codelist` VALUES('J',623,'전라권','무안','무안','무안군,신안군','e080f5');
INSERT INTO `codelist` VALUES('J',624,'전라권','영암','영암','영암군','e080f5');
INSERT INTO `codelist` VALUES('J',625,'전라권','화순','화순','화순군','e080f5');
INSERT INTO `codelist` VALUES('M',626,'전라권','진안','진안','진안군','e080f5');
INSERT INTO `codelist` VALUES('J',627,'전라권','장흥','장흥','장흥군,완도군 금당면','e080f5');
INSERT INTO `codelist` VALUES('J',628,'전라권','진도','진도','진도군','e080f5');
INSERT INTO `codelist` VALUES('J',629,'전라권','고창','고창','고창군','e080f5');
INSERT INTO `codelist` VALUES('J',630,'전라권','광주','서광주','서구','e080f5');
INSERT INTO `codelist` VALUES('J',631,'전라권','광주','광산','광산구','e080f5');
INSERT INTO `codelist` VALUES('M',632,'전라권','전주','북전주','덕진구','e080f5');
INSERT INTO `codelist` VALUES('J',633,'전라권','순창','순창','순창군','e080f5');
INSERT INTO `codelist` VALUES('J',634,'전라권','완도','완도','완도군,생일면 덕우도','e080f5');
INSERT INTO `codelist` VALUES('M',635,'전라권','부안','부안','부안군','e080f5');
INSERT INTO `codelist` VALUES('J',636,'전라권','장수','장수','장수군','e080f5');
INSERT INTO `codelist` VALUES('J',637,'전라권','함평','함평','함평군','e080f5');
INSERT INTO `codelist` VALUES('L',701,'강원권','강릉','강릉','강릉시,양양군 현남면','d4ab3b');
INSERT INTO `codelist` VALUES('L',702,'강원권','삼척','삼척','삼척시','d4ab3b');
INSERT INTO `codelist` VALUES('L',703,'강원권','영월','영월','영월군','d4ab3b');
INSERT INTO `codelist` VALUES('W',704,'강원권','속초','속초','속초시,양양군','d4ab3b');
INSERT INTO `codelist` VALUES('L',705,'강원권','동해','동해','동해시','d4ab3b');
INSERT INTO `codelist` VALUES('L',706,'강원권','원주','원주','원주시','d4ab3b');
INSERT INTO `codelist` VALUES('W',708,'강원권','춘천','춘천','춘천시','d4ab3b');
INSERT INTO `codelist` VALUES('W',709,'강원권','홍천','홍천','홍천군','d4ab3b');
INSERT INTO `codelist` VALUES('L',710,'강원권','태백','태백','태백시,삼척시(도계읍,하장면)','d4ab3b');
INSERT INTO `codelist` VALUES('L',711,'강원권','평창','평창','평창군','d4ab3b');
INSERT INTO `codelist` VALUES('W',712,'강원권','화천','화천','화천군,춘천시 사북면','d4ab3b');
INSERT INTO `codelist` VALUES('W',713,'강원권','인제','인제','양구군,인제군','d4ab3b');
INSERT INTO `codelist` VALUES('L',714,'강원권','횡성','횡성','횡성군','d4ab3b');
INSERT INTO `codelist` VALUES('L',715,'강원권','정선','정선','정선군','d4ab3b');
INSERT INTO `codelist` VALUES('W',716,'강원권','고성','고성','고성군','d4ab3b');
INSERT INTO `codelist` VALUES('W',717,'강원권','철원','철원','철원군','d4ab3b');
INSERT INTO `codelist` VALUES('Y',801,'제주권','제주','제주','제주시,우도면,추자면,서귀포시(대정읍,성산읍,안덕면,표선면)','ebd496');
INSERT INTO `codelist` VALUES('Y',802,'제주권','서귀포','서귀포','서귀포시','ebd496');
COMMIT;
